### PR TITLE
raven event upgrades

### PR DESCRIPTION
**Pull request by visualphoenix**
update to use client.send_event (client.event is now deprecated). fill out more of the event if records are available.

### CODE REVIEW

**Comment by y-ken** [comment]
Hi @visualphoenix 
Thank you very much!
Could you please update test code?

**Comment by visualphoenix** [comment]
i must say i'm not very familiar with how to fix the broken travis integration. i'm also unfamiliar with webmock. do you know how to fix your existing tests?

**Comment by y-ken** [comment]
Sure. After merge it, I'm going to check what was occurred!
Thanks!

**Comment by y-ken** [comment]
Updated test code
https://github.com/y-ken/fluent-plugin-sentry/commit/fee25bdf4a1ea93e9855913968df88eb0c0d6135
https://travis-ci.org/y-ken/fluent-plugin-sentry/builds/88292334

**Pull request merged**
