### PR TITLE
Version for Ruby 2

### PR DESCRIPTION
**Pull request by ppp0**

### CODE REVIEW

**Comment by ppp0** [comment]
@y-ken This version would then be compatible with newer ruby environments!

Please review and release if you think it is a good idea

Thank you ありがとう ございました

**Comment by ppp0** [comment]
Depends on #7 

See also https://github.com/tagomoris/fluent-plugin-forest/pull/26 and https://github.com/tagomoris/fluent-plugin-forest/pull/27 for a very similar issue

**Comment by y-ken** [comment]
Nice!

**Comment by y-ken** [comment]
I think better to test with ruby-2.1 and 2.2 mainly. For ruby-1.9 user, it keep tests only for fluentd-v0.10
https://github.com/y-ken/fluent-plugin-sentry/blob/master/.travis.yml

**Comment by ppp0** [comment]
Not needed. Completely solved in #7

**Pull request closed without merging**
